### PR TITLE
product luxe missing sections

### PR DESCRIPTION
**Pull request by ted-dino**

### CODE REVIEW

**Comment by gbertl** [comment]
paupdate ng title ng PR

**Comment by gbertl** [comment]
Screenshot from 2022-11-07 14-45-58

**Comment by gbertl** [comment]
Screenshot from 2022-11-07 14-48-41

**Comment by gbertl** [comment]
Palipat nalang  between neto yung reviews
Screenshot from 2022-11-07 14-49-13

kasi ganto sa live
Screenshot from 2022-11-07 14-49-20

**no need to clone sa live ha kasi may reviews section na sa `products-luxe.html` yun ang ilipat mo**

**Comment by ted-dino** [comment]
> Screenshot from 2022-11-07 14-45-58

delete **Public Transit** input checkbox

**Comment by gbertl** [comment]
sa mobile pala imatch mo nalang sa desktop na ginawa mo i mean yung mga sections 

like kunwari dapat wala tong section na to
Screenshot from 2022-11-07 15-02-18

**Comment by ted-dino** [comment]
> 

delete ko nalang siguro to. wala na man talaga ata to kahit large screen

**Comment by gbertl** [comment]
> > 
> 
> delete ko nalang siguro to. wala na man talaga ata to kahit large screen

alin jan

**Comment by ted-dino** [comment]
> sa mobile pala imatch mo nalang sa desktop na ginawa mo i mean yung mga sections
> 
> like kunwari dapat wala tong section na to Screenshot from 2022-11-07 15-02-18

eto

**Comment by gbertl** [comment]
> > sa mobile pala imatch mo nalang sa desktop na ginawa mo i mean yung mga sections
> > like kunwari dapat wala tong section na to Screenshot from 2022-11-07 15-02-18
> 
> eto

yes tama imatch mo lang

**Comment by ted-dino** [comment]
> Palipat nalang between neto yung reviews Screenshot from 2022-11-07 14-49-13
> 
> kasi ganto sa live Screenshot from 2022-11-07 14-49-20
> 
> **no need to clone sa live ha kasi may reviews section na sa `products-luxe.html` yun ang ilipat mo**

done

**Pull request merged**
